# Generated by Django 4.0.2 on 2022-02-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='accountingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateEvent', models.DateTimeField()),
                ('account', models.CharField(max_length=50)),
                ('subaccount', models.CharField(max_length=50)),
                ('valueEvent', models.FloatField()),
                ('descriptionEvent', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='subaccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ledgerAccount', models.CharField(max_length=50)),
            ],
        ),
    ]
